### ISSUE TITLE
GetEntries silently failed

### ISSUE THREAD

**Issue by anarcat** [Strubbl/wallabago#10]
From the point of view of wallabako, the GetEntries function can sometimes silently fail. For example in [this issue](https://gitlab.com/anarcat/wallabako/issues/24), I have found that when the machine running wallabako gets suspended for extended periods of time (*while wallabako is running!*), GetEntries can return an apparent success while still actually failing to do the request. In my use case, this means returning "0 unread entries" (the "zero value" of that field of course), which means all the files get removed! Nothing shows up in the logs, because `fmt.Fprintf` is used instead of (say) `log.Fprintf` either, so the error looks completely mysterious.

In general, this is an API design flaw that permeates the library: instead of printing errors on stderr with `fmt`, we should *return* errors like I proposed in #5. For example, in GetEntries instead of:

		fmt.Fprintf(os.Stderr, "getEntries: json unmarshal failed: %v\n", err)

we should:

                return e, fmt.Errorf("getEntries: json unmarshal failed: %v\n", err)

... or possible just:

     return e, err

Similarly, in that funciton `bodyByteGetterFunc` should be able to raise errors in the idiomatic golang way as well.

I understand this can be an annoying change to perform as it is somewhat far-ranging, but it seems important to uncover mistakes like the bug I have found...

Thanks!

**Comment by Strubbl** [comment]
Thanks for bringing this to my attention. I am going to fix this now

**Comment by Strubbl** [comment]
Okay, this error should be fixed with release 2.0.0
This changes since 1.0.0 can be viewed here: https://github.com/Strubbl/wallabago/compare/1.0.0...2.0.0

It would be really cool if you can review the changes.

**Comment by anarcat** [comment]
wow, that's great! i didn't expect you'd fix this so quickly... I am not sure I'll have time to actually test this before next week, but at first glance the patchset looks good, congrats!

**Comment by Strubbl** [comment]
No problem. I was in the mood today and it was really bad design with all those prints. I am looking forward to your test results.

**Comment by anarcat** [comment]
okay, i've tested the new code and I think it will resolve my issue. i still need to catchup with the API changes in #5: I have a bunch of code in wallabako that needs to move to wallabago... but i'm in a rush so apologies if i can't do this just yet. :)
