### ISSUE TITLE
precompiled binary release

### ISSUE THREAD

**Issue by m040601** [Strubbl/wallabago#12]
would it be possible to release a binary on github or gitlab ?
it would sure help quickly testing it out, and maybe creating a package for Linux distros (Arch AUR)

**Comment by Strubbl** [comment]
Hmm, i am not sure if i get your issue right. This is just a library you can use in your go program. so i cannot distribute an executable here.

**Comment by m040601** [comment]
I understand, now that you updated the Readme.
There are already other projects that build a cli application based on it,

> Projects using wallabago
> wallabako - wallabag client for Kobo readers
> wallabag-stats - draws a chart for unread and total articles in your wallabag instance
> wallabag-add-article - commandline utility to add an article to wallabag
>

**Comment by m040601** [comment]
But could you the release a binary for,
https://gitlab.com/Strubbl/wallabag-add-article
You are also it's author right ?



> you can use in your go program. 

Not everyone has the entire Go distribution installed or is a developer. I know that go compiling is easy. But releasing a binary, would make it easier for end users.  Example, for those wanting to create a package for a Linux distro, based on the binary (ex. Archlinux AUR). Or quickly test  it on the Desktop (or eReader device).


This is what wallabako does on gitlab, (I think he uses gitlab's free job/pipeline/ci ???)
> https://gitlab.com/anarcat/wallabako
> .....download the binary to an ereader ....
> .... or you can also download the standalone binaries 
> for 64 bits (aka amd64 or x86_64) or ARM (e.g. Raspberry PI).....

Thanks in advance

**Comment by Strubbl** [comment]
Hi @m040601 , yes, for the projects i am maintaining, i can release a binary. Unfortunately [goreleaser](https://goreleaser.com/) does not support Gitlab yet. There is [an open issue](https://github.com/goreleaser/goreleaser/pull/809) and this is currently worked on. If that is finished i am following up the binary releases. 

Therefore i am closing this issue here. Please add an issue in the other repositories if you want.
