### ISSUE TITLE
Add compatibility with modules semver

### ISSUE THREAD

**Issue by agarciamontoro** [Strubbl/wallabago#13]
I tried to use wallabago while using go modules (I'm using go 1.13) and I could not use any version higher than `v1.0.0`.

The reason is that go modules only understand tags that start with the `v`. I tested it with a fork and it works smoothly when the release tag is, for example, `v2.0.0` instead of `2.0.0`: https://github.com/agarciamontoro/wallabago/releases/tag/v2.0.0

Is it possible to stick to this convention so that `wallabago` can be used with go modules? Thank you!

**Comment by Strubbl** [comment]
Yes, i am going to change that.

**Comment by Strubbl** [comment]
I just pushed the tags with the v as prefix. I keep the old ones for reference and try to remember this issue for future tags.

**Comment by Strubbl** [comment]
if you want to add your project to the list at the end of the readme, feel free to send me a PR

**Comment by agarciamontoro** [comment]
Thank you!

> if you want to add your project to the list at the end of the readme, feel free to send me a PR

As soon as I have it ready!
