### ISSUE TITLE
use new API that doesn't require passwords

### ISSUE THREAD

**Issue by anarcat** [Strubbl/wallabago#9]
upstream finally implemented better oauth support (https://github.com/wallabag/wallabag/issues/2800). the means we do not need to store the cleartext user password anymore nor use it in the API, starting with 2.3.0: the client secret strings are enough to get a token.

i am not sure how to handle this. should we break backwards compatibility with older releases? should we detect the API version and require the right configuration depending on the API?

i needed this for wallabako but figured here was actually where this was implemented.

**Comment by Strubbl** [comment]
we can create a new version, that breaks backwards compatibility. 
I do not have the time to support older releases. older releases have to use an older version of the lib then. maybe i can create one last version before the lib is moved to wbg core 2.3

**Comment by Strubbl** [comment]
I thought i could work on this today, but unfortunately the mentioned issue at wallabag core is still not solved.

**Comment by anarcat** [comment]
yep, this is totally embarrassing, i guess this can be closed until wallabag learns about authentication. :(
